name: Crack it
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "resHuman"
          replace: "result"
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Initial commit'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Noob-Stranger
          commit_user_email: 85062690+Noob-Stranger@users.noreply.github.com
